import { getDb } from "@/db";
import { userPlayerHistory, picks, playerMatchStats, matchScores, fixtures } from "@/db/schema";
import { eq, and, sql } from "drizzle-orm";

/**
 * User–Player Selection Journey Tracker
 *
 * Increments supporter pick counts, calculates average performance ratings
 * when selected, tracks highest rated matches, and updates total fantasy contribution
 * points generated after match finalisation.
 */

export async function updateUserPlayerJourney(
  fixtureId: string,
  competitionId: string
): Promise<number> {
  const db = getDb();

  // 1. Fetch the finalised fixture
  const [fixture] = await db
    .select()
    .from(fixtures)
    .where(eq(fixtures.id, fixtureId))
    .limit(1);

  if (!fixture || !fixture.finalisedAt) return 0;

  // 2. Fetch all user picks lock entries for this match
  const userPicks = await db
    .select()
    .from(picks)
    .where(eq(picks.fixtureId, fixtureId));

  if (!userPicks.length) return 0;

  // 3. Fetch player ratings for this match
  const matchRatings = await db
    .select()
    .from(playerMatchStats)
    .where(eq(playerMatchStats.fixtureId, fixtureId));

  const ratingsMap = new Map(matchRatings.map((r) => [r.playerId, r.finalRating]));

  // 4. Fetch match scores to map total contribution points generated by each user
  const scores = await db
    .select()
    .from(matchScores)
    .where(eq(matchScores.fixtureId, fixtureId));

  const scoreMap = new Map(scores.map((s) => [s.wallet, s]));

  let updatedCount = 0;

  for (const pick of userPicks) {
    const wallet = pick.wallet;
    const userScore = scoreMap.get(wallet);
    const supporterPoints = userScore ? userScore.contribution : 0.0;

    // A user drafts three players: attacker, midfielder, defender
    const selectedPlayerIds = [pick.attackerId, pick.midfielderId, pick.defenderId];

    for (const playerId of selectedPlayerIds) {
      if (!playerId) continue;

      const finalRating = ratingsMap.get(playerId) ?? null;

      // Check if entry already exists in user_player_history
      const [existing] = await db
        .select()
        .from(userPlayerHistory)
        .where(
          and(
            eq(userPlayerHistory.wallet, wallet),
            eq(userPlayerHistory.playerId, playerId),
            eq(userPlayerHistory.competitionId, competitionId)
          )
        )
        .limit(1);

      if (existing) {
        const nextTimesSelected = existing.timesSelected + 1;
        const nextCompletedSelections = existing.completedSelections + 1;
        const nextTotalRating = existing.totalRatingWhenSelected + (finalRating ?? 0.0);
        const nextAvgRating = nextTotalRating / nextCompletedSelections;
        const nextPoints = existing.supporterPointsGenerated + supporterPoints;

        let bestFixtureId = existing.bestFixtureId;
        if (finalRating !== null) {
          // If we had a best rating, compare. Otherwise check if this rating is better.
          const bestRatingVal = existing.bestFixtureId ? (ratingsMap.get(existing.bestFixtureId) ?? 0) : 0;
          if (finalRating > bestRatingVal) {
            bestFixtureId = fixtureId;
          }
        }

        await db
          .update(userPlayerHistory)
          .set({
            timesSelected: nextTimesSelected,
            completedSelections: nextCompletedSelections,
            totalRatingWhenSelected: nextTotalRating,
            averageRatingWhenSelected: Math.round(nextAvgRating * 100) / 100,
            supporterPointsGenerated: Math.round(nextPoints * 100) / 100,
            bestFixtureId,
            lastSelectedFixtureId: fixtureId,
            updatedAt: new Date().toISOString(),
          })
          .where(
            and(
              eq(userPlayerHistory.wallet, wallet),
              eq(userPlayerHistory.playerId, playerId),
              eq(userPlayerHistory.competitionId, competitionId)
            )
          );
      } else {
        await db.insert(userPlayerHistory).values({
          wallet,
          playerId,
          competitionId,
          timesSelected: 1,
          completedSelections: 1,
          totalRatingWhenSelected: finalRating ?? 0.0,
          averageRatingWhenSelected: finalRating,
          positionComparisonsWon: 0,
          supporterPointsGenerated: Math.round(supporterPoints * 100) / 100,
          bestFixtureId: finalRating !== null ? fixtureId : null,
          lastSelectedFixtureId: fixtureId,
          updatedAt: new Date().toISOString(),
        });
      }

      updatedCount++;
    }
  }

  return updatedCount;
}
